/*
 * QMud Project
 * Copyright (c) 2026 Panagiotis Kalogiratos (Nodens)
 *
 * File: LuaFunctionMetadata.cpp
 * Role: Function metadata registry used to describe Lua-exposed APIs for validation, discovery, and compatibility
 * checks.
 */

#include "LuaFunctionTypes.h"

// Canonical Lua function metadata source of truth used by `utils.functionlist`,
// `utils.functionargs`, and API inventory exports.
const InternalFunctionMetadata kInternalFunctionMetadataTable[] = {
    {"Accelerator",               "( Key , Send )"                                                                      },
    {"AcceleratorList",           "( )"                                                                                 },
    {"AcceleratorTo",             "( Key , Send , SendTo )"                                                             },
    {"Activate",                  "( )"                                                                                 },
    {"ActivateClient",            "( )"                                                                                 },
    {"ActivateNotepad",           "( Title )"                                                                           },
    {"AddAlias",                  "( AliasName , MatchText , ResponseText , Flags , ScriptName )"                       },
    {"AddFont",                   "( PathName )"                                                                        },
    {"AddMapperComment",          "( Comment )"                                                                         },
    {"AddSpellCheckWord",         "( OriginalWord , ActionCode , ReplacementWord )"                                     },
    {"AddTimer",                  "( TimerName , Hour , Minute , Second , ResponseText , Flags , ScriptName )"          },
    {"AddToMapper",               "( Direction , Reverse )"                                                             },
    {"AddTrigger",
     "( TriggerName , MatchText , ResponseText , Flags , Colour , Wildcard , SoundFileName , ScriptName )"              },
    {"AddTriggerEx",              "( TriggerName , MatchText , ResponseText , Flags , Colour , Wildcard , SoundFileName , "
                     "ScriptName , SendTo , Sequence )"                                             },
    {"AdjustColour",              "( Colour , Method )"                                                                 },
    {"ANSI",                      "( Code )"                                                                            },
    {"AnsiNote",                  "( Text )"                                                                            },
    {"AppendToNotepad",           "( Title , Contents )"                                                                },
    {"ArrayClear",                "( Name )"                                                                            },
    {"ArrayCount",                "( )"                                                                                 },
    {"ArrayCreate",               "( Name )"                                                                            },
    {"ArrayDelete",               "( Name )"                                                                            },
    {"ArrayDeleteKey",            "( Name , Key )"                                                                      },
    {"ArrayExists",               "( Name )"                                                                            },
    {"ArrayExport",               "( Name , Delimiter )"                                                                },
    {"ArrayExportKeys",           "( Name , Delimiter )"                                                                },
    {"ArrayGet",                  "( Name , Key )"                                                                      },
    {"ArrayGetFirstKey",          "( Name )"                                                                            },
    {"ArrayGetLastKey",           "( Name )"                                                                            },
    {"ArrayImport",               "( Name , Values , Delimiter )"                                                       },
    {"ArrayKeyExists",            "( Name , Key )"                                                                      },
    {"ArrayList",                 "( )"                                                                                 },
    {"ArrayListAll",              "( )"                                                                                 },
    {"ArrayListKeys",             "( Name )"                                                                            },
    {"ArrayListValues",           "( Name )"                                                                            },
    {"ArraySet",                  "( Name , Key , Value )"                                                              },
    {"ArraySize",                 "( Name )"                                                                            },
    {"Base64Decode",              "( Text )"                                                                            },
    {"Base64Encode",              "( Text , MultiLine )"                                                                },
    {"BlendPixel",                "( Blend , Base , Mode , Opacity )"                                                   },
    {"BoldColour",                "( WhichColour , NewValue )"                                                          },
    {"Bookmark",                  "( LineNumber , Set )"                                                                },
    {"BroadcastPlugin",           "( Message , Text )"                                                                  },
    {"CallPlugin",                "( PluginID , Routine , Argument )"                                                   },
    {"ChangeDir",                 "( Path )"                                                                            },
    {"ChatAcceptCalls",           "( Port )"                                                                            },
    {"ChatCall",                  "( Server , Port )"                                                                   },
    {"ChatCallzChat",             "( Server , Port )"                                                                   },
    {"ChatDisconnect",            "( ID )"                                                                              },
    {"ChatDisconnectAll",         "( )"                                                                                 },
    {"ChatEverybody",             "( Message , Emote )"                                                                 },
    {"ChatGetID",                 "( Who )"                                                                             },
    {"ChatGroup",                 "( Group , Message , Emote )"                                                         },
    {"ChatID",                    "( ID , Message , Emote )"                                                            },
    {"ChatMessage",               "( ID , Message , Text )"                                                             },
    {"ChatNameChange",            "( NewName )"                                                                         },
    {"ChatNote",                  "( NoteType , Message )"                                                              },
    {"ChatPasteEverybody",        "( )"                                                                                 },
    {"ChatPasteText",             "( ID )"                                                                              },
    {"ChatPeekConnections",       "( ID )"                                                                              },
    {"ChatPersonal",              "( Who , Message , Emote )"                                                           },
    {"ChatPing",                  "( ID )"                                                                              },
    {"ChatRequestConnections",    "( ID )"                                                                              },
    {"ChatSendFile",              "( ID , FileName )"                                                                   },
    {"ChatStopAcceptingCalls",    "( )"                                                                                 },
    {"ChatStopFileTransfer",      "( ID )"                                                                              },
    {"CloseLog",                  "( )"                                                                                 },
    {"CloseNotepad",              "( Title , QuerySave )"                                                               },
    {"ColourNameToRGB",           "( Name )"                                                                            },
    {"ColourNote",                "( TextColour , BackgroundColour , Text )"                                            },
    {"ColourTell",                "( TextColour , BackgroundColour , Text )"                                            },
    {"Connect",                   "( )"                                                                                 },
    {"CreateGUID",                "( )"                                                                                 },
    {"CustomColourBackground",    "( WhichColour , NewValue )"                                                          },
    {"CustomColourText",          "( WhichColour , NewValue )"                                                          },
    {"DatabaseChanges",           "( DbName )"                                                                          },
    {"DatabaseClose",             "( DbName )"                                                                          },
    {"DatabaseColumnName",        "( DbName , Column )"                                                                 },
    {"DatabaseColumnNames",       "( DbName )"                                                                          },
    {"DatabaseColumns",           "( DbName )"                                                                          },
    {"DatabaseColumnText",        "( DbName , Column )"                                                                 },
    {"DatabaseColumnType",        "( DbName , Column )"                                                                 },
    {"DatabaseColumnValue",       "( DbName , Column )"                                                                 },
    {"DatabaseColumnValues",      "( DbName )"                                                                          },
    {"DatabaseError",             "( DbName )"                                                                          },
    {"DatabaseExec",              "( DbName , Sql )"                                                                    },
    {"DatabaseFinalize",          "( DbName )"                                                                          },
    {"DatabaseGetField",          "( DbName , Sql )"                                                                    },
    {"DatabaseInfo",              "( DbName , InfoType )"                                                               },
    {"DatabaseLastInsertRowid",   "( DbName )"                                                                          },
    {"DatabaseList",              "( )"                                                                                 },
    {"DatabaseOpen",              "( DbName , Filename , Flags )"                                                       },
    {"DatabasePrepare",           "( DbName , Sql )"                                                                    },
    {"DatabaseReset",             "( DbName )"                                                                          },
    {"DatabaseStep",              "( DbName )"                                                                          },
    {"DatabaseTotalChanges",      "( DbName )"                                                                          },
    {"Debug",                     "( Command )"                                                                         },
    {"DeleteAlias",               "( AliasName )"                                                                       },
    {"DeleteAliasGroup",          "( GroupName )"                                                                       },
    {"DeleteAllMapItems",         "( )"                                                                                 },
    {"DeleteCommandHistory",      "( )"                                                                                 },
    {"DeleteGroup",               "( GroupName )"                                                                       },
    {"DeleteLastMapItem",         "( )"                                                                                 },
    {"DeleteLines",               "( Count )"                                                                           },
    {"DeleteOutput",              "( )"                                                                                 },
    {"DeleteTemporaryAliases",    "( )"                                                                                 },
    {"DeleteTemporaryTimers",     "( )"                                                                                 },
    {"DeleteTemporaryTriggers",   "( )"                                                                                 },
    {"DeleteTimer",               "( TimerName )"                                                                       },
    {"DeleteTimerGroup",          "( GroupName )"                                                                       },
    {"DeleteTrigger",             "( TriggerName )"                                                                     },
    {"DeleteTriggerGroup",        "( GroupName )"                                                                       },
    {"DeleteVariable",            "( VariableName )"                                                                    },
    {"DiscardQueue",              "( )"                                                                                 },
    {"Disconnect",                "( )"                                                                                 },
    {"DoAfter",                   "( Seconds , SendText )"                                                              },
    {"DoAfterNote",               "( Seconds , NoteText )"                                                              },
    {"DoAfterSpecial",            "( Seconds , SendText , SendTo )"                                                     },
    {"DoAfterSpeedWalk",          "( Seconds , SendText )"                                                              },
    {"DoCommand",                 "( Command )"                                                                         },
    {"EchoInput",                 "( )"                                                                                 },
    {"EditDistance",              "( Source , Target )"                                                                 },
    {"EnableAlias",               "( AliasName , Enabled )"                                                             },
    {"EnableAliasGroup",          "( GroupName , Enabled )"                                                             },
    {"EnableGroup",               "( GroupName , Enabled )"                                                             },
    {"EnableMapping",             "( Enabled )"                                                                         },
    {"EnablePlugin",              "( PluginID , Enabled )"                                                              },
    {"EnableTimer",               "( TimerName , Enabled )"                                                             },
    {"EnableTimerGroup",          "( GroupName , Enabled )"                                                             },
    {"EnableTrigger",             "( TriggerName , Enabled )"                                                           },
    {"EnableTriggerGroup",        "( GroupName , Enabled )"                                                             },
    {"ErrorDesc",                 "( Code )"                                                                            },
    {"EvaluateSpeedwalk",         "( SpeedWalkString )"                                                                 },
    {"Execute",                   "( Command )"                                                                         },
    {"ExportXML",                 "( Type , Name )"                                                                     },
    {"FilterPixel",               "( Pixel , Operation , Options )"                                                     },
    {"FixupEscapeSequences",      "( Source )"                                                                          },
    {"FixupHTML",                 "( StringToConvert )"                                                                 },
    {"FlashIcon",                 "( )"                                                                                 },
    {"FlushLog",                  "( )"                                                                                 },
    {"GenerateName",              "( )"                                                                                 },
    {"GetAlias",                  "( AliasName , MatchText , ResponseText , Parameter , Flags , ScriptName )"           },
    {"GetAliasInfo",              "( AliasName , InfoType )"                                                            },
    {"GetAliasList",              "( )"                                                                                 },
    {"GetAliasOption",            "( AliasName , OptionName )"                                                          },
    {"GetAliasWildcard",          "( AliasName , WildcardName )"                                                        },
    {"GetAlphaOption",            "( OptionName )"                                                                      },
    {"GetAlphaOptionList",        "( )"                                                                                 },
    {"GetBoldColour",             "( )"                                                                                 },
    {"GetChatInfo",               "( ChatID , InfoType )"                                                               },
    {"GetChatList",               "( )"                                                                                 },
    {"GetChatOption",             "( ID , OptionName )"                                                                 },
    {"GetClipboard",              "( )"                                                                                 },
    {"GetCommand",                "( )"                                                                                 },
    {"GetCommandList",            "( Count )"                                                                           },
    {"GetConnectDuration",        "( )"                                                                                 },
    {"GetConnectTime",            "( )"                                                                                 },
    {"GetCurrentValue",           "( OptionName )"                                                                      },
    {"GetCustomColourBackground", "( )"                                                                                 },
    {"GetCustomColourName",       "( WhichColour )"                                                                     },
    {"GetCustomColourText",       "( )"                                                                                 },
    {"GetDefaultValue",           "( OptionName )"                                                                      },
    {"GetDeviceCaps",             "( Index )"                                                                           },
    {"GetEchoInput",              "( )"                                                                                 },
    {"GetEntity",                 "( Name )"                                                                            },
    {"GetFrame",                  "( )"                                                                                 },
    {"GetGlobalOption",           "( OptionName )"                                                                      },
    {"GetGlobalOptionList",       "( )"                                                                                 },
    {"GetHostAddress",            "( HostName )"                                                                        },
    {"GetHostName",               "( IPaddress )"                                                                       },
    {"GetInfo",                   "( InfoType )"                                                                        },
    {"GetInternalCommandsList",   "( )"                                                                                 },
    {"GetLineCount",              "( )"                                                                                 },
    {"GetLineInfo",               "( LineNumber , InfoType )"                                                           },
    {"GetLinesInBufferCount",     "( )"                                                                                 },
    {"GetLoadedValue",            "( OptionName )"                                                                      },
    {"GetLogInput",               "( )"                                                                                 },
    {"GetLogNotes",               "( )"                                                                                 },
    {"GetLogOutput",              "( )"                                                                                 },
    {"GetMainWindowPosition",     "( )"                                                                                 },
    {"GetMapColour",              "( Which )"                                                                           },
    {"GetMapping",                "( )"                                                                                 },
    {"GetMappingCount",           "( )"                                                                                 },
    {"GetMappingItem",            "( Item )"                                                                            },
    {"GetMappingString",          "( )"                                                                                 },
    {"GetNormalColour",           "( )"                                                                                 },
    {"GetNoteColour",             "( )"                                                                                 },
    {"GetNoteColourBack",         "( )"                                                                                 },
    {"GetNoteColourFore",         "( )"                                                                                 },
    {"GetNotepadLength",          "( Title )"                                                                           },
    {"GetNotepadList",            "( All )"                                                                             },
    {"GetNotepadText",            "( Title )"                                                                           },
    {"GetNotepadWindowPosition",  "( Title )"                                                                           },
    {"GetNotes",                  "( )"                                                                                 },
    {"GetNoteStyle",              "( )"                                                                                 },
    {"GetOption",                 "( OptionName )"                                                                      },
    {"GetOptionList",             "( )"                                                                                 },
    {"GetPluginAliasInfo",        "( PluginID , AliasName , InfoType )"                                                 },
    {"GetPluginAliasList",        "( PluginID )"                                                                        },
    {"GetPluginAliasOption",      "( PluginID , AliasName , OptionName )"                                               },
    {"GetPluginID",               "( )"                                                                                 },
    {"GetPluginInfo",             "( PluginID , InfoType )"                                                             },
    {"GetPluginList",             "( )"                                                                                 },
    {"GetPluginName",             "( )"                                                                                 },
    {"GetPluginTimerInfo",        "( PluginID , TimerName , InfoType )"                                                 },
    {"GetPluginTimerList",        "( PluginID )"                                                                        },
    {"GetPluginTimerOption",      "( PluginID , TimerName , OptionName )"                                               },
    {"GetPluginTriggerInfo",      "( PluginID , TriggerName , InfoType )"                                               },
    {"GetPluginTriggerList",      "( PluginID )"                                                                        },
    {"GetPluginTriggerOption",    "( PluginID , TriggerName , OptionName )"                                             },
    {"GetPluginVariable",         "( PluginID , VariableName )"                                                         },
    {"GetPluginVariableList",     "( PluginID )"                                                                        },
    {"GetQueue",                  "( )"                                                                                 },
    {"GetReceivedBytes",          "( )"                                                                                 },
    {"GetRecentLines",            "( Count )"                                                                           },
    {"GetRemoveMapReverses",      "( )"                                                                                 },
    {"GetScriptTime",             "( )"                                                                                 },
    {"GetSelectionEndColumn",     "( )"                                                                                 },
    {"GetSelectionEndLine",       "( )"                                                                                 },
    {"GetSelectionStartColumn",   "( )"                                                                                 },
    {"GetSelectionStartLine",     "( )"                                                                                 },
    {"GetSentBytes",              "( )"                                                                                 },
    {"GetSoundStatus",            "( Buffer )"                                                                          },
    {"GetSpeedWalkDelay",         "( )"                                                                                 },
    {"GetStatusTime",             "( )"                                                                                 },
    {"GetStyleInfo",              "( LineNumber , StyleNumber , InfoType )"                                             },
    {"GetSysColor",               "( Index )"                                                                           },
    {"GetSystemMetrics",          "( Index )"                                                                           },
    {"GetTimer",                  "( TimerName , Hour , Minute , Second , ResponseText , Flags , ScriptName )"          },
    {"GetTimerInfo",              "( TimerName , InfoType )"                                                            },
    {"GetTimerList",              "( )"                                                                                 },
    {"GetTimerOption",            "( TimerName , OptionName )"                                                          },
    {"GetTrace",                  "( )"                                                                                 },
    {"GetTrigger",
     "( TriggerName , MatchText , ResponseText , Flags , Colour , Wildcard , SoundFileName , ScriptName )"              },
    {"GetTriggerInfo",            "( TriggerName , InfoType )"                                                          },
    {"GetTriggerList",            "( )"                                                                                 },
    {"GetTriggerOption",          "( TriggerName , OptionName )"                                                        },
    {"GetTriggerWildcard",        "( TriggerName , WildcardName )"                                                      },
    {"GetUdpPort",                "( First , Last )"                                                                    },
    {"GetUniqueID",               "( )"                                                                                 },
    {"GetUniqueNumber",           "( )"                                                                                 },
    {"GetVariable",               "( VariableName )"                                                                    },
    {"GetVariableList",           "( )"                                                                                 },
    {"GetWorld",                  "( WorldName )"                                                                       },
    {"GetWorldById",              "( WorldID )"                                                                         },
    {"GetWorldID",                "( )"                                                                                 },
    {"GetWorldIdList",            "( )"                                                                                 },
    {"GetWorldList",              "( )"                                                                                 },
    {"GetWorldWindowPosition",    "( )"                                                                                 },
    {"GetWorldWindowPositionX",   "( Which )"                                                                           },
    {"GetXMLEntity",              "( Entity )"                                                                          },
    {"Hash",                      "( Text )"                                                                            },
    {"Help",                      "( Name )"                                                                            },
    {"Hyperlink",                 "( Action , Text , Hint , TextColour , BackColour , URL )"                            },
    {"ImportXML",                 "( XML )"                                                                             },
    {"Info",                      "( Message )"                                                                         },
    {"InfoBackground",            "( Name )"                                                                            },
    {"InfoClear",                 "( )"                                                                                 },
    {"InfoColour",                "( Name )"                                                                            },
    {"InfoFont",                  "( FontName , Size , Style )"                                                         },
    {"IsAlias",                   "( AliasName )"                                                                       },
    {"IsConnected",               "( )"                                                                                 },
    {"IsLogOpen",                 "( )"                                                                                 },
    {"IsPluginInstalled",         "( PluginID )"                                                                        },
    {"IsTimer",                   "( TimerName )"                                                                       },
    {"IsTrigger",                 "( TriggerName )"                                                                     },
    {"LoadPlugin",                "( FileName )"                                                                        },
    {"LogInput",                  "( )"                                                                                 },
    {"LogNotes",                  "( )"                                                                                 },
    {"LogOutput",                 "( )"                                                                                 },
    {"LogSend",                   "( Message )"                                                                         },
    {"MakeRegularExpression",     "( Text )"                                                                            },
    {"MapColour",                 "( Original , Replacement )"                                                          },
    {"MapColourList",             "( )"                                                                                 },
    {"Mapping",                   "( )"                                                                                 },
    {"Menu",                      "( Items , Default )"                                                                 },
    {"Metaphone",                 "( Word , Length )"                                                                   },
    {"MoveMainWindow",            "( Left , Top , Width , Height )"                                                     },
    {"MoveNotepadWindow",         "( Title , Left , Top , Width , Height )"                                             },
    {"MoveWorldWindow",           "( Left , Top , Width , Height )"                                                     },
    {"MoveWorldWindowX",          "( Left , Top , Width , Height , Which )"                                             },
    {"MtRand",                    "( )"                                                                                 },
    {"MtSrand",                   "( Seed )"                                                                            },
    {"NormalColour",              "( WhichColour , NewValue )"                                                          },
    {"Note",                      "( Message )"                                                                         },
    {"NoteColour",                "( )"                                                                                 },
    {"NoteColourBack",            "( )"                                                                                 },
    {"NoteColourFore",            "( )"                                                                                 },
    {"NoteColourName",            "( Foreground , Background )"                                                         },
    {"NoteColourRGB",             "( Foreground , Background )"                                                         },
    {"NoteHr",                    "( )"                                                                                 },
    {"NotepadColour",             "( Title , TextColour , BackgroundColour )"                                           },
    {"NotepadFont",               "( Title , FontName , Size , Style , Charset )"                                       },
    {"NotepadReadOnly",           "( Title , ReadOnly )"                                                                },
    {"NotepadSaveMethod",         "( Title , Method )"                                                                  },
    {"NoteStyle",                 "( Style )"                                                                           },
    {"Open",                      "( FileName )"                                                                        },
    {"OpenBrowser",               "( URL )"                                                                             },
    {"OpenLog",                   "( LogFileName , Append )"                                                            },
    {"PasteCommand",              "( Text )"                                                                            },
    {"Pause",                     "( Flag )"                                                                            },
    {"PickColour",                "( Suggested )"                                                                       },
    {"PlaySound",                 "( Buffer , FileName , Loop , Volume , Pan )"                                         },
    {"PlaySoundMemory",           "( )"                                                                                 },
    {"PluginSupports",            "( PluginID , Routine )"                                                              },
    {"print",                     "( )"                                                                                 },
    {"PushCommand",               "( )"                                                                                 },
    {"Queue",                     "( Message , Echo )"                                                                  },
    {"ReadNamesFile",             "( FileName )"                                                                        },
    {"Redraw",                    "( )"                                                                                 },
    {"ReloadPlugin",              "( PluginID )"                                                                        },
    {"RemoveBacktracks",          "( Path )"                                                                            },
    {"RemoveMapReverses",         "( )"                                                                                 },
    {"Repaint",                   "( )"                                                                                 },
    {"Replace",                   "( Source , SearchFor , ReplaceWith , Multiple )"                                     },
    {"ReplaceNotepad",            "( Title , Contents )"                                                                },
    {"Reset",                     "( )"                                                                                 },
    {"ResetIP",                   "( )"                                                                                 },
    {"ResetStatusTime",           "( )"                                                                                 },
    {"ResetTimer",                "( TimerName )"                                                                       },
    {"ResetTimers",               "( )"                                                                                 },
    {"ReverseSpeedwalk",          "( SpeedWalkString )"                                                                 },
    {"RGBColourToName",           "( Colour )"                                                                          },
    {"Save",                      "( Name )"                                                                            },
    {"SaveNotepad",               "( Title , FileName , ReplaceExisting )"                                              },
    {"SaveState",                 "( )"                                                                                 },
    {"SelectCommand",             "( )"                                                                                 },
    {"Send",                      "( Message )"                                                                         },
    {"SendImmediate",             "( Message )"                                                                         },
    {"SendNoEcho",                "( Message )"                                                                         },
    {"SendPkt",                   "( Packet )"                                                                          },
    {"SendPush",                  "( Message )"                                                                         },
    {"SendSpecial",               "( Message , Echo , Queue , Log , History )"                                          },
    {"SendToNotepad",             "( Title , Contents )"                                                                },
    {"SetAliasOption",            "( AliasName , OptionName , Value )"                                                  },
    {"SetAlphaOption",            "( OptionName , Value )"                                                              },
    {"SetAsyncResultFilter",      "( Filters )"                                                                         },
    {"SetBackgroundColour",       "( Colour )"                                                                          },
    {"SetBackgroundImage",        "( FileName , Mode )"                                                                 },
    {"SetBoldColour",             "( )"                                                                                 },
    {"SetChanged",                "( ChangedFlag )"                                                                     },
    {"SetChatOption",             "( ID , OptionName , Value )"                                                         },
    {"SetClipboard",              "( Text )"                                                                            },
    {"SetCommand",                "( Message )"                                                                         },
    {"SetCommandSelection",       "( First , Last )"                                                                    },
    {"SetCommandWindowHeight",    "( Height )"                                                                          },
    {"SetCursor",                 "( Cursor )"                                                                          },
    {"SetCustomColourBackground", "( )"                                                                                 },
    {"SetCustomColourName",       "( WhichColour , Name )"                                                              },
    {"SetCustomColourText",       "( )"                                                                                 },
    {"SetEchoInput",              "( )"                                                                                 },
    {"SetEntity",                 "( Name , Contents )"                                                                 },
    {"SetForegroundImage",        "( FileName , Mode )"                                                                 },
    {"SetFrameBackgroundColour",  "( Colour )"                                                                          },
    {"SetInputFont",              "( FontName , PointSize , Weight , Italic )"                                          },
    {"SetLogInput",               "( )"                                                                                 },
    {"SetLogNotes",               "( )"                                                                                 },
    {"SetLogOutput",              "( )"                                                                                 },
    {"SetMainTitle",              "( Title )"                                                                           },
    {"SetMapping",                "( )"                                                                                 },
    {"SetNormalColour",           "( )"                                                                                 },
    {"SetNoteColour",             "( )"                                                                                 },
    {"SetNoteColourBack",         "( )"                                                                                 },
    {"SetNoteColourFore",         "( )"                                                                                 },
    {"SetNotes",                  "( Message )"                                                                         },
    {"SetOption",                 "( OptionName , Value )"                                                              },
    {"SetOutputFont",             "( FontName , PointSize )"                                                            },
    {"SetRemoveMapReverses",      "( )"                                                                                 },
    {"SetScroll",                 "( Position ,  Visible )"                                                             },
    {"SetSelection",              "( StartLine , EndLine , StartColumn , EndColumn )"                                   },
    {"SetSpeedWalkDelay",         "( )"                                                                                 },
    {"SetStatus",                 "( Message )"                                                                         },
    {"SetTimerOption",            "( TimerName , OptionName , Value )"                                                  },
    {"SetTitle",                  "( Title )"                                                                           },
    {"SetToolBarPosition",        "( Which , Float , Side , Top , Left )"                                               },
    {"SetTrace",                  "( )"                                                                                 },
    {"SetTriggerOption",          "( TriggerName , OptionName , Value )"                                                },
    {"SetUnseenLines",            "( Counter )"                                                                         },
    {"SetVariable",               "( VariableName , Contents )"                                                         },
    {"SetWorldWindowStatus",      "( Parameter )"                                                                       },
    {"ShiftTabCompleteItem",      "( Item )"                                                                            },
    {"ShowInfoBar",               "( Visible )"                                                                         },
    {"Simulate",                  "( Text )"                                                                            },
    {"Sound",                     "( SoundFileName )"                                                                   },
    {"SpeedWalkDelay",            "( )"                                                                                 },
    {"SpellCheck",                "( Text )"                                                                            },
    {"SpellCheckCommand",         "( StartCol , EndCol )"                                                               },
    {"SpellCheckDlg",             "( Text )"                                                                            },
    {"StopEvaluatingTriggers",    "( AllPlugins )"                                                                      },
    {"StopSound",                 "( Buffer )"                                                                          },
    {"StripANSI",                 "( Message )"                                                                         },
    {"Tell",                      "( Message )"                                                                         },
    {"TextRectangle",             "( Left , Top , Right , Bottom , BorderOffset , BorderColour , BorderWidth , "
                      "OutsideFillColour , OutsideFillStyle )"                                     },
    {"Trace",                     "( )"                                                                                 },
    {"TraceOut",                  "( Message )"                                                                         },
    {"TranslateDebug",            "( Message )"                                                                         },
    {"TranslateGerman",           "( Text )"                                                                            },
    {"Transparency",              "( Key , Amount )"                                                                    },
    {"Trim",                      "( Source )"                                                                          },
    {"UdpListen",                 "( IP , Port , Script )"                                                              },
    {"UdpPortList",               "( )"                                                                                 },
    {"UdpSend",                   "( IP , Port , Text )"                                                                },
    {"UnloadPlugin",              "( PluginID )"                                                                        },
    {"Version",                   "( )"                                                                                 },
    {"WindowAddHotspot",
     "( WindowName , HotspotId , Left , Top , Right , Bottom , MouseOver , CancelMouseOver , MouseDown , "
     "CancelMouseDown , MouseUp , TooltipText , Cursor , Flags )"                                                       },
    {"WindowArc",
     "( WindowName , Left , Top , Right , Bottom , x1 , y1 , x2 , y2 , PenColour , PenStyle , PenWidth )"               },
    {"WindowBezier",              "( WindowName , Points , PenColour , PenStyle , PenWidth )"                           },
    {"WindowBlendImage",          "( WindowName , ImageId , Left , Top , Right , Bottom , Mode , Opacity , SrcLeft , "
                         "SrcTop , SrcRight , SrcBottom )"                                      },
    {"WindowCircleOp",            "( WindowName , Action , Left , Top , Right , Bottom , PenColour , PenStyle , "
                       "PenWidth , BrushColour , BrushStyle , Extra1 , Extra2 , Extra3 , Extra4 )"},
    {"WindowCreate",              "( WindowName , Left , Top , Width , Height , Position , Flags , BackgroundColour )"  },
    {"WindowCreateImage",         "( WindowName , ImageId , Row8 , Row7 , Row6 , Row5 , Row4 , Row3 , Row2 , Row1 )"    },
    {"WindowDelete",              "( WindowName )"                                                                      },
    {"WindowDeleteAllHotspots",   "( WindowName )"                                                                      },
    {"WindowDeleteHotspot",       "( WindowName , HotspotId )"                                                          },
    {"WindowDragHandler",         "( WindowName , HotspotId , MoveCallback , ReleaseCallback , Flags )"                 },
    {"WindowDrawImage",           "( WindowName , ImageId , Left , Top , Right , Bottom , Mode , SrcLeft , SrcTop , "
                        "SrcRight , SrcBottom )"                                                 },
    {"WindowDrawImageAlpha",
     "( WindowName , ImageId , Left , Top , Right , Bottom , Opacity , SrcLeft , SrcTop )"                              },
    {"WindowFilter",              "( WindowName , Left , Top , Right , Bottom , Operation , Options )"                  },
    {"WindowFont",                "( WindowName , FontId , FontName , Size , Bold , Italic , Underline , Strikeout , "
                   "Charset , PitchAndFamily )"                                                       },
    {"WindowFontInfo",            "( WindowName , FontId , InfoType )"                                                  },
    {"WindowFontList",            "( WindowName )"                                                                      },
    {"WindowGetImageAlpha",       "( WindowName , ImageId , Left , Top , Right , Bottom , SrcLeft , SrcTop )"           },
    {"WindowGetPixel",            "( WindowName , x , y )"                                                              },
    {"WindowGradient",            "( WindowName , Left , Top , Right , Bottom , StartColour , EndColour , Mode )"       },
    {"WindowHotspotInfo",         "( WindowName , HotspotId , InfoType )"                                               },
    {"WindowHotspotList",         "( WindowName )"                                                                      },
    {"WindowHotspotTooltip",      "( WindowName , HotspotId , TooltipText )"                                            },
    {"WindowImageFromWindow",     "( WindowName , ImageId , SourceWindow )"                                             },
    {"WindowImageInfo",           "( WindowName , ImageId , InfoType )"                                                 },
    {"WindowImageList",           "( WindowName )"                                                                      },
    {"WindowImageOp",             "( WindowName , Action , Left , Top , Right , Bottom , PenColour , PenStyle , PenWidth "
                      ", BrushColour , ImageId , EllipseWidth , EllipseHeight )"                   },
    {"WindowInfo",                "( WindowName , InfoType )"                                                           },
    {"WindowLine",                "( WindowName , x1 , y1 , x2 , y2 , PenColour , PenStyle , PenWidth )"                },
    {"WindowList",                "( )"                                                                                 },
    {"WindowLoadImage",           "( WindowName , ImageId , FileName )"                                                 },
    {"WindowLoadImageMemory",     "( )"                                                                                 },
    {"WindowMenu",                "( WindowName , Left , Top , Items )"                                                 },
    {"WindowMergeImageAlpha",     "( WindowName , ImageId , MaskId , Left , Top , Right , Bottom , Mode , "
                              "Opacity , SrcLeft , SrcTop , SrcRight , SrcBottom )"        },
    {"WindowMoveHotspot",         "( WindowName , HotspotId , Left , Top , Right , Bottom )"                            },
    {"WindowPolygon",             "( WindowName , Points , PenColour , PenStyle , PenWidth , BrushColour , BrushStyle , "
                      "Close , Winding )"                                                          },
    {"WindowPosition",            "( WindowName , Left , Top , Position , Flags )"                                      },
    {"WindowRectOp",              "( WindowName , Action , Left , Top , Right , Bottom , Colour1 , Colour2 )"           },
    {"WindowResize",              "( WindowName , Width , Height , BackgroundColour )"                                  },
    {"WindowScrollwheelHandler",  "( WindowName , HotspotId , MoveCallback )"                                           },
    {"WindowSetPixel",            "( WindowName , x , y , Colour )"                                                     },
    {"WindowSetZOrder",           "( WindowName , Order )"                                                              },
    {"WindowShow",                "( WindowName , Show )"                                                               },
    {"WindowText",                "( WindowName , FontId , Text , Left , Top , Right , Bottom , Colour , Unicode )"     },
    {"WindowTextWidth",           "( WindowName , FontId , Text , Unicode )"                                            },
    {"WindowTransformImage",      "( WindowName , ImageId , Left , Top , Mode , Mxx , Mxy , Myx , Myy ) "               },
    {"WindowWrite",               "( WindowName , FileName )"                                                           },
    {"WorldAddress",              "( )"                                                                                 },
    {"WorldName",                 "( )"                                                                                 },
    {"WorldPort",                 "( )"                                                                                 },
    {"WriteLog",                  "( Message )"                                                                         },
    {"",                          ""                                                                                    }  // End of table marker
};
